### PR TITLE
feat(cloud.logs): filebeat 6.8 - 17 modules

### PR DESCRIPTION
**Pull request by pdepaepe**
Hello,

This PR will allow Logs Data Platform customers to get from our Logstash wizard a ready to use configuration for following applications supported by Filebeat 6.8 modules (delivered the 18th June 2019) :

- apache2 (error + access)
- auditd
- mysql (log + slowlog)
- nginx (error + access)
- system (auth + syslog)
- elasticsearch
- haproxy
- icinga
- iis
- kafka
- kibana
- logstash
- mongodb
- osquery
- postgresql
- redit
- traefik

Please note that as some of the filters rules expect in text such characters '\/' i had to disable for this file the eslint rule: no-useless-escape.

Thanks for the review, merge & prod time.

### CODE REVIEW

**Comment by pdepaepe** [comment]
You’re absolutely right, but this is not yet available, so please consider this one.

**Comment by marie-j** [comment]
I agree with @antleblanc, this is impossible to maintain. Imo, it should be returned by API and adding this as a constant is not a solution (even as a quick win)

**Comment by antleblanc** [comment]
@marie-j Here is the internal ticket reference related to an API change request: OB-1887.

**Comment by antleblanc** [comment]
Internal ticket reference: **MANAGER-2969**

**Comment by jleveugle** [comment]
Hello @pdepaepe,
Your pull request is now closed due to inactivity.
Feel free to re-open it if you have any update.
Anna Bot for OVH UX <3

**Pull request merged**
