### PR TITLE
fix(cloud): openstack terminal copy/paste on safari

### PR DESCRIPTION
**Pull request by snigle**
(move hterm to xterm.js)

Signed-off-by: Ludovic Lamarche <ludovic.lamarche@corp.ovh.com>

### Benefits

Better terminal with less bug on all browsers.

ref: SCFRCA-1795

### CODE REVIEW

**Comment by antleblanc** [comment]
@snigle there is a conflict.
@Netnix do you have any updates from QA?

**Comment by snigle** [comment]
@antleblanc fixed conflict

**Comment by ovh-cds** [comment]
CDS Report build-yarn#5420.0 ✘  
* Stage 1
  * deps ✘

**Comment by ovh-cds** [comment]
CDS Report build-yarn#5421.0 ✘  
* Stage 1
  * deps ✘

**Comment by antleblanc** [comment]
@snigle Due to a recent merge you now have a small conflict. Could you please resolve it :) thx.

**Pull request merged**
