### PR TITLE
fix(navbar): revamp style and texts

### PR DESCRIPTION
**Pull request by FredericEspiau**
## Revamp Navbar
MBE-188

Related to:
- ovh-ux/ovh-manager-web#872
- ovh-ux/ovh-manager-dedicated#877
- ovh-ux/ovh-manager-telecom#1214

### CODE REVIEW

**Comment by jleveugle** [comment]
Hello @FredericEspiau,
Your pull request is now closed due to inactivity.
Feel free to re-open it if you have any update.
Anna Bot for OVH UX <3

**Comment by ovh-cds** [comment]
CDS Report build-manager#659.0 ✘  
* Stage 1
  * Build dependencies and inject Sentry ✔ 
* Stage 2
  * Build manager CA ✔ 
  * Build manager EU ✔ 
  * Build manager US ✔ 
  * Tests ✘

**Comment by ovh-cds** [comment]
CDS Report build-manager#668.0 ✘  
* Stage 1
  * Build dependencies and inject Sentry ✘

**Comment by jleveugle** [comment]
Hello @FredericEspiau,
Your pull request is now closed due to inactivity.
Feel free to re-open it if you have any update.
Anna Bot for OVH UX <3

**Pull request merged**
