### PR TITLE
refactor(common): move common service to cuc

### PR DESCRIPTION
**Pull request by cbourgois**
### Description of the Change

b24d2063 — refactor(common): move common service to cuc

### Related PR

* [x] https://github.com/ovh-ux/ng-ovh-cloud-universe-components/pull/3

ref: OM-302

/cc @jleveugle @frenautvh @antleblanc

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report build-manager#857.0 ✘  
* Stage 1
  * Build dependencies and inject Sentry ✔ 
* Stage 2
  * Build manager CA ✘  
  * Build manager EU ✘  
  * Build manager US ✘  
  * Tests ✘

**Comment by ovh-cds** [comment]
CDS Report build-manager#858.0 ✘  
* Stage 1
  * Build dependencies and inject Sentry ✔ 
* Stage 2
  * Build manager CA ✘  
  * Build manager EU ✘  
  * Build manager US ✘  
  * Tests ✘

**Comment by ovh-cds** [comment]
CDS Report build-manager#859.0 ■   
* Stage 1
  * Build dependencies and inject Sentry ✔ 
* Stage 2
  * Build manager CA ■   
  * Build manager EU ■   
  * Build manager US ✘  
  * Tests ✔

**Comment by ovh-cds** [comment]
CDS Report build-manager#859.1 ✘  
* Stage 1
  * Build dependencies and inject Sentry ✔ 
* Stage 2
  * Build manager CA ✘  
  * Build manager EU ✔ 
  * Build manager US ✘  
  * Tests ✔

**Comment by ovh-cds** [comment]
CDS Report build-manager#859.2 ■   
* Stage 1
  * Build dependencies and inject Sentry ✔ 
* Stage 2
  * Build manager CA ✘  
  * Build manager EU ■   
  * Build manager US ✘  
  * Tests ✔

**Comment by ovh-cds** [comment]
CDS Report build-manager#864.0 ✘  
* Stage 1
  * Build dependencies and inject Sentry ✔ 
* Stage 2
  * Build manager CA ✘  
  * Build manager EU ✔ 
  * Build manager US ✘  
  * Tests ✔

**Comment by cbourgois** [comment]
Rebased on `develop`

**Pull request merged**
